spring:
  jmx:
    default-domain: mybatis
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/salary_management_system
    username: root
    password: 970505
mybatis:
  # 指定实体类包路径
  typeAliasesPackage: com.fsq.fsqsalary.po
  # 指定xml文件扫描路径
  mapper-locations: classpath*:mapper/*.xml
